# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190128_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description2',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fax',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secretary',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='-'),
        ),
    ]
