# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-28 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190128_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='org_name',
        ),
    ]
