# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190128_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='org_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
